"""
===============================================================================
🎙️ EVENTS MODULE — Voice Agent Streaming Protocol
===============================================================================
This module defines the typed events that flow through our streaming pipeline.
Think of these events as "packages" passed along an assembly line:

  [Browser Mic] ➔ (Audio Bytes)
       ➔ [AssemblyAI STT] ➔ (STTChunkEvent / STTOutputEvent)
       ➔ [LangChain Agent] ➔ (AgentChunkEvent / AgentCompleteEvent)
       ➔ [Cartesia TTS]   ➔ (TTSChunkEvent) ➔ [Browser Speaker]

Students: Every event is a simple Python dataclass with a unique 'type' tag
so our server and frontend know exactly how to handle each message!
===============================================================================
"""

from __future__ import annotations
import asyncio
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Literal, Optional


@dataclass
class VoiceAgentEvent:
    """
    Base event for the voice agent pipeline.
    All specific event types inherit from this class.
    """
    type: str = "base"

    def to_dict(self) -> dict[str, Any]:
        """Convert the event object into a dictionary for JSON serialization."""
        return {k: v for k, v in self.__dict__.items() if not k.startswith("_")}


@dataclass
class STTChunkEvent(VoiceAgentEvent):
    """
    Partial Speech-to-Text Transcript Event.
    Emitted in real-time as the user is speaking words (e.g., 'Yes...', 'Yes, I would...').
    Used by the UI to show live transcription without interrupting the user.
    """
    transcript: str = ""
    type: str = "stt_chunk"

    @classmethod
    def create(cls, transcript: str) -> "STTChunkEvent":
        return cls(transcript=transcript, type="stt_chunk")


@dataclass
class STTOutputEvent(VoiceAgentEvent):
    """
    Finalized Speech-to-Text Transcript Event.
    Emitted when Voice Activity Detection (VAD) detects that the user finished
    speaking a complete sentence. This is the TRIGGER that activates the LangChain Agent.
    """
    transcript: str = ""
    type: str = "stt_output"

    @classmethod
    def create(cls, transcript: str) -> "STTOutputEvent":
        return cls(transcript=transcript, type="stt_output")


@dataclass
class AgentChunkEvent(VoiceAgentEvent):
    """
    Incremental text token generated by the LangChain Agent.
    Emitted word-by-word as the LLM thinks. This allows Text-to-Speech (TTS)
    to begin synthesizing audio immediately without waiting for the full response.
    """
    text: str = ""
    type: str = "agent_chunk"

    @classmethod
    def create(cls, text: str) -> "AgentChunkEvent":
        return cls(text=text, type="agent_chunk")


@dataclass
class AgentCompleteEvent(VoiceAgentEvent):
    """
    Complete final text response from the agent for a given turn.
    Signals that the agent has finished generating its answer.
    """
    response: str = ""
    type: str = "agent_complete"

    @classmethod
    def create(cls, response: str) -> "AgentCompleteEvent":
        return cls(response=response, type="agent_complete")


@dataclass
class TTSChunkEvent(VoiceAgentEvent):
    """
    Synthesized Audio Chunk from the Text-to-Speech (TTS) engine.
    Contains raw audio bytes (WAV/PCM) ready to be played through the user's speaker.
    """
    audio: bytes = b""
    format: str = "pcm"
    sample_rate: int = 44100
    type: str = "tts_chunk"

    @classmethod
    def create(cls, audio: bytes, format: str = "pcm", sample_rate: int = 44100) -> "TTSChunkEvent":
        return cls(audio=audio, format=format, sample_rate=sample_rate, type="tts_chunk")


@dataclass
class StatusEvent(VoiceAgentEvent):
    """
    Pipeline State Event (e.g., 'idle', 'listening', 'thinking', 'speaking', 'error').
    Informs the frontend to update visual status indicators and animations.
    """
    status: Literal["idle", "listening", "thinking", "speaking", "error"] = "idle"
    message: str = ""
    type: str = "status"

    @classmethod
    def create(cls, status: Literal["idle", "listening", "thinking", "speaking", "error"], message: str = "") -> "StatusEvent":
        return cls(status=status, message=message, type="status")


async def merge_async_iters(*iterators: AsyncIterator[Any]) -> AsyncIterator[Any]:
    """
    Merge multiple async generators into a single combined async stream.
    
    Why this is important for students:
    In real-time voice, we need to process incoming events and receive audio chunks
    CONCURRENTLY without blocking each other. This helper merges multiple queues
    into one unified stream.
    """
    queue: asyncio.Queue[Any] = asyncio.Queue()
    active_tasks = len(iterators)
    sentinel = object()

    async def _pump(it: AsyncIterator[Any]):
        nonlocal active_tasks
        try:
            async for item in it:
                await queue.put(item)
        except Exception as err:
            await queue.put(err)
        finally:
            active_tasks -= 1
            if active_tasks == 0:
                await queue.put(sentinel)

    tasks = [asyncio.create_task(_pump(it)) for it in iterators]

    try:
        while True:
            item = await queue.get()
            if item is sentinel:
                break
            if isinstance(item, Exception):
                raise item
            yield item
    finally:
        for t in tasks:
            t.cancel()
            with asyncio.CancelledError:
                pass
